### ISSUE TITLE
Multiple errors in console with default setup

### ISSUE THREAD

**Issue by shuther** [boxyhq/saas-starter-kit#1573]
I guess I am missing something but during my first setup/signup and I am getting few errors:
Could you help to pinpoint the problem?
```
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Recording is off, propagating context in a non-recording span
Current logger will be overwritten from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:392:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/index.ts:11:70)
    at (api)/./pages/api/teams/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:252:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2Findex.ts&middlewareConfigBase64=e30%3D!:11:83)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:572:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:573:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:573:47
Current logger will overwrite one already registered from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:392:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/index.ts:11:70)
    at (api)/./pages/api/teams/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:252:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2Findex.ts&middlewareConfigBase64=e30%3D!:11:83)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:572:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:573:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams.js:573:47
@opentelemetry/api: Registered a global for diag v1.9.0.
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
 GET /api/teams 200 in 195ms
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
 GET /_next/data/development/en/teams/team1/settings.json?slug=team1 200 in 661ms
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Recording is off, propagating context in a non-recording span
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
 ✓ Compiled /api/teams/[slug] in 153ms (1147 modules)
Current logger will be overwritten from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:402:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/[slug]/index.ts:11:70)
    at (api)/./pages/api/teams/[slug]/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D!:11:88)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:272:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:592:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:47
Current logger will overwrite one already registered from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:402:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/[slug]/index.ts:11:70)
    at (api)/./pages/api/teams/[slug]/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D!:11:88)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:272:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:592:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:47
@opentelemetry/api: Registered a global for diag v1.9.0.
Recording is off, propagating context in a non-recording span
Recording is off, propagating context in a non-recording span
 GET /api/teams/team1 200 in 389ms
@opentelemetry/instrumentation-http http instrumentation incomingRequest
Recording is off, propagating context in a non-recording span


Recording is off, propagating context in a non-recording span
 ✓ Compiled /api/teams/[slug] in 198ms (1117 modules)
 ✓ Compiled (1121 modules)
Current logger will be overwritten from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:402:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/[slug]/index.ts:11:70)
    at (api)/./pages/api/teams/[slug]/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D!:11:88)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:272:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:592:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:47
Current logger will overwrite one already registered from Error
    at DiagAPI.setLogger (Documents/devP/saas-starter-s/node_modules/@opentelemetry/api/build/src/api/diag.js:65:37)
    at initializeMetrics (Documents/devP/saas-starter-s/node_modules/@boxyhq/metrics/dist/init.js:42:20)
    at eval (webpack-internal:///(api)/./lib/metrics.ts:12:67)
    at (api)/./lib/metrics.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:402:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./pages/api/teams/[slug]/index.ts:11:70)
    at (api)/./pages/api/teams/[slug]/index.ts (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:262:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D!:11:88)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2Fteams%2F%5Bslug%5D&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2Fteams%2F%5Bslug%5D%2Findex.ts&middlewareConfigBase64=e30%3D! (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:272:1)
    at __webpack_require__ (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:592:39)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:83
    at __webpack_require__.X (Documents/devP/saas-starter-s/.next/server/webpack-api-runtime.js:116:21)
    at Documents/devP/saas-starter-s/.next/server/pages/api/teams/[slug].js:593:47
@opentelemetry/api: Registered a global for diag v1.9.0.
```

**Comment by deepakprabhakara** [comment]
@shuther Are you setting any Otel env params?

**Comment by deepakprabhakara** [comment]
Please comment out `OTEL_EXPORTER_DEBUG=true` in the env file, we'll push a change as well.
